a = float(input("enter а: "))
b = float(input("enter b: "))
print("addition result: ", a + b)
print("subtraction result: ", a - b)
print("multiplication result: ", a * b)
print("division result: ", a / b)
print("exponentiation result: ", a**b)
print("integer division result: ", divmod(a, b)[0])
print("division by modulus result: ", divmod(a, b)[1])
